// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.24.4
// source: gogoproto/gogo.proto

/* eslint-disable */

export const protobufPackage = "gogoproto";
