// @generated
// This file is @generated by prost-build.
/// Module is the config object of the builder module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// Authority defines the custom module authority.
    /// If not set, defaults to the governance module.
    #[prost(string, tag="2")]
    pub authority: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
