// @generated
// This file is @generated by prost-build.
/// Module is the config object of the liquid module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// authority defines the custom module authority. If not set, defaults to the
    /// governance module.
    #[prost(string, tag="1")]
    pub authority: ::prost::alloc::string::String,
    /// bech32_prefix_validator is the bech32 validator prefix for the app.
    #[prost(string, tag="2")]
    pub bech32_prefix_validator: ::prost::alloc::string::String,
    /// bech32_prefix_consensus is the bech32 consensus node prefix for the app.
    #[prost(string, tag="3")]
    pub bech32_prefix_consensus: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
