// @generated
// This file is @generated by prost-build.
/// ExtensionData is a data structure that can be used in transaction extensions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtensionData {
    /// protocol_id is the identifier of the protocol
    /// the field is not used internally but it is validated for correctness
    #[prost(string, tag="1")]
    pub protocol_id: ::prost::alloc::string::String,
    /// protocol_version is the identifier of the protocol version
    /// the field is not used internally but it is validated for correctness
    #[prost(string, tag="2")]
    pub protocol_version: ::prost::alloc::string::String,
    /// arbitrary bytes data that can be used to store any data
    /// the field is not used internally but it is validated and must be provided
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
