[package]
name = "liquidity-provider"
version = "1.0.0"
authors = []


[addresses]
# Do not change
initia_std = "0x1"
std = "0x1"

# Address of uinit:uusdc pool
pair = "0xdbf06c48af3984ec6d9ae8a9aa7dbb0bb1e784aa9b8c4a5681af660cf8558d7d"

# Address of uinit token
asset = "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"

# Contract owner
me = "0xf5397c546c82981c01190465d86965fd43584ef5e8887dadf57a56c9b6ac1dd7"

# Receives LP tokens
recipient = "0xf5397c546c82981c01190465d86965fd43584ef5e8887dadf57a56c9b6ac1dd7"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm", subdir = "precompile/modules/initia_stdlib", rev = "v0.6.1" }
